# main menu navigation
menu:
  Home: /
  About: /about
  Archive: /archives

widgets:
  - tag
  - archive
  - recent_posts
  - category
  - profile

# social config
social:
  zhihu: https://www.zhihu.com/people/di-san-miao-mo-de-shuang-qu-zheng-qie-43
  twitter: https://twitter.com/archibate
  facebook: /
  linkedin:
  instagram: /
  github: archibate

user:
  name: archibate
  avatar: /images/avatar.jpg
  location: Shanghai, China
  description: 温馨的小窝是否正定
  footnotes: 温馨小窝不需要脚注

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: true
  repo: archibate/archibate.github.io


# documents: https://valine.js.org/quickstart.html
comment_valine:
  enable: false
  appId:
  appKey:

comment_disqus:
    enable: false
    url:  https://archibate.top
    name: archibate.top

# dark
# light
# user-can-set
appearance: auto

# Miscellaneous
favicon: /images/favicon.png

# Google Analytics
ga_track_id:
ga_domain:

# Baidu Analytics
ba_track_id:

# picture of about page
about_pic: about.png
